# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 578e5a351dc6fca12b852440126e19157ff8e44b77231eb6c404480a51c54fd621d32c73b4e7d40dfdc358292b0957117d5fddc2c5722673f985e74a26ad7f6f

test:
  secret_key_base: cea8a29a8571285a5de65809e0cb495dee7264cfbc10e187c2c98ef66eda52853ca82ae7bdeb16c7cf3a8116ffc2eeca395a962891213fabc7bd235fa0ec12ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
